name: CI

on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Check out the repo
      - uses: actions/checkout@v3

      # Install .NET
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '5.0.x'

      # Build everything
      - name: Build the executables
        run: |
          dotnet build --configuration Release

      # Run tests
      - name: Test
        run: dotnet test --configuration Release --no-build

      # Build NuGet package
      - name: Build the NuGet package
        run: dotnet pack --configuration Release --no-build

      # Push the NuGet package
      - name: Push the NuGet package
        if: contains(github.ref, 'refs/tags/')
        run: dotnet nuget push --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json src\bin\Release\*.nupkg
